### ISSUE TITLE
Fatal error when parsing an empty string

### ISSUE THREAD

**Issue by bogdanbolchis** [crescentflare/SimpleMarkdownParser#2]
I am running into a crash when trying to parse an empty markdown string. I can fix it on the caller side, but it should be fixed in SimpleMarkdownParser.

`fatal error: Can't form a Character from an empty String`

![screen shot 2016-10-26 at 13 01 52](https://cloud.githubusercontent.com/assets/2010912/19723637/75bfe382-9b7c-11e6-9329-97dcac1735fc.png)
![screen shot 2016-10-26 at 13 02 13](https://cloud.githubusercontent.com/assets/2010912/19723639/75ffd14a-9b7c-11e6-99e8-48d5d2fa59bc.png)

**Comment by crescentflare** [comment]
Which version are you using? A fix was made for that in the 0.5.0 version and onwards.

**Comment by bogdanbolchis** [comment]
I'm using '~> 0.4.0'. In that case the issue will fix itself when we upgrade the dependency.

**Comment by crescentflare** [comment]
Closed because the issue doesn't seem to appear anymore
