### ISSUE TITLE
[iOS] Standard mark down link crashes.

### ISSUE THREAD

**Issue by DanTug** [crescentflare/SimpleMarkdownParser#5]
When trying to parse markdown with a title like this: ```[I'm an inline-style link with title](https://www.google.com "Google's Homepage")```
the parser crashes on line 53 in class DefaultMarkdownAttributedStringGenerator, function "applyAttribute". 

I suspect that "URL(string: extra)!" crashes because extra = "https://www.google.com "Google's Homepage" and the URL cannot be created. 

Would be super nice with a fix for this.

**Comment by crescentflare** [comment]
I'll check to see if I can discard the optional title in the markdown parser, in the meantime you can workaround this issue by overriding the DefaultMarkdownAttributedStringGenerator class and removing the optional title before passing it to the super class

**Comment by DanTug** [comment]
That would be great. Thanks for the super quick response!

**Comment by DanTug** [comment]
@crescentflare The workaround fixed the crash, thanks for the tip. But I suppose it's a nice issue to fix in the library as a whole.

**Comment by crescentflare** [comment]
The library has been updated to 0.6.2 with the fix, closing issue
