### ISSUE TITLE
[Android] List item alignment off

### ISSUE THREAD

**Issue by MagnusHedlundUsTwo** [crescentflare/SimpleMarkdownParser#6]
When using ordered and unordered lists the list token gets drawn with a y value of  _bottom - p.descent()_ which leads to the result: 
![off](https://user-images.githubusercontent.com/19567810/55879585-45c55a00-5b9f-11e9-8b8b-8af719943e32.png)

If instead use baseline as y value, i get the result:
![baseline](https://user-images.githubusercontent.com/19567810/55879691-7a391600-5b9f-11e9-9c5f-2c4a00a997d2.png)

Is there a reason for not using baseline instead?

Kind regards
// Magnus

**Comment by crescentflare** [comment]
I've implemented the change and everything still works, I guess there was no reason to use the descent calculation (other than it being old code). Version 0.6.5 has the fix.

**Comment by MagnusHedlundUsTwo** [comment]
Nice! Thanks a lot :)
